# Generated by Django 4.1.5 on 2023-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_cost_salesorder_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='test_field',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='test_two',
        ),
    ]
