# Generated by Django 4.1.5 on 2023-01-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_salesorder_account_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='account_one',
        ),
    ]
